Repository Hiteshydv001/Guard-AI-Designing-Remote-Proctoring-System, pull requests merged in 2025-01, with the labels that each got.

#29 Enhanced README and Contributing Guide for Improved Usability
  CONTRIBUTING.md
  README.md
Labels: SWOC, BEGINNER

#44 add auth to Guard AI
  main-web-vecel/app/Signin/[[...sign-in]]/page.tsx
  main-web-vecel/app/Signup/[[...sign-up]]/page.tsx
  main-web-vecel/app/layout.tsx
  main-web-vecel/components/layout/navbar.tsx
  main-web-vecel/middleware.ts
Labels: SWOC, ADVANCED

#41 created head tracking feature
  README.md Head_Tracking
  head_app.py
  head_pose_detection.py
  index.html
  index2.html
Labels: SWOC, INTERMEDIATE

#47 Head pose estimation integration with flask app
  HeadPoseEstimation/demo.py
  HeadPoseEstimation/face_detection.py
  HeadPoseEstimation/face_landmarker.py
  HeadPoseEstimation/session.py
  Suspicious Activity/User1/2025-01-12/22_50_36/Captures/Frequent Head Movement/capture_1.jpg
  Suspicious Activity/User1/2025-01-12/22_50_36/Captures/More than 1 face/capture_2.jpg
  Suspicious Activity/User1/2025-01-12/22_50_36/Captures/Prolonged Looking Away/capture_0.jpg
  Suspicious Activity/User1/2025-01-12/22_50_36/logs.json
  serve.py
  server.py
  templates/calibrate.html
  templates/hello.html
  templates/index.html
  templates/proctering_screen.html
  templates/stop_proctering.html
Labels: SWOC, INTERMEDIATE

#48 feat: improved index website
  index.html
Labels: SWOC, INTERMEDIATE

#51 fix: added project banner to index website
  index.html
Labels: SWOC, BEGINNER

#53 feat: add ui consistency to github readme in index website
  index.html
Labels: SWOC, BEGINNER

#60 Enhance Documentation with Visual and Structural Updates
  CONTRIBUTING.md
  FAQ.md
  images/discord.png
  images/points.png
  images/project.png
Labels: SWOC, BEGINNER

#61 feat: fixed theme color mismatches in index website
  assets/css/styles.css
  index.html
Labels: good first issue, SWOC, BEGINNER

#50 feat: improved the hero section
  main-web-vecel/app/(root)/page.tsx
  main-web-vecel/app/(root)/proctor/page.tsx
  main-web-vecel/components/layout/sections/features.tsx
  main-web-vecel/components/layout/sections/hero.tsx
  main-web-vecel/components/layout/sections/sponsors.tsx
  main-web-vecel/package-lock.json
  main-web-vecel/package.json
  main-web-vecel/public/s1.json
  main-web-vecel/public/s2.json
  main-web-vecel/public/security-dark.json
  main-web-vecel/public/security-light.json
Labels: SWOC, INTERMEDIATE
