Repository Hiteshydv001/Guard-AI-Designing-Remote-Proctoring-System, pull requests merged in 2025-02, with the labels that each got.

#77 move animation fetch part to page.tsx in root folder
  main-web-vecel/.env.local
  main-web-vecel/app/(root)/page.tsx
  main-web-vecel/components/layout/sections/hero.tsx
  main-web-vecel/components/layout/theme-provider.tsx
  main-web-vecel/components/ui/animation-container.tsx
  main-web-vecel/components/ui/placeholder.tsx
Labels: SWOC, INTERMEDIATE

#84 Fix/sponser section
  main-web-vecel/components/layout/sections/sponsors.tsx
  main-web-vecel/pnpm-lock.yaml
  main-web-vecel/tailwind.config.ts
Labels: good first issue, DWOC, level 1

#86 fix: issue in footer
  main-web-vecel/components/layout/sections/footer.tsx
Labels: good first issue, DWOC, level 1

#88 add candidate /proctor side
  main-web-vecel/.env
  main-web-vecel/app/(root)/candidate/page.tsx
  main-web-vecel/app/(root)/layout.tsx
  main-web-vecel/app/(root)/proctor/page.tsx
  main-web-vecel/app/globals.css
  main-web-vecel/app/page.tsx
  main-web-vecel/components.json
  main-web-vecel/components/ui/accordion.tsx
  main-web-vecel/components/ui/alert-dialog.tsx
  main-web-vecel/components/ui/badge.tsx
  main-web-vecel/components/ui/button.tsx
  main-web-vecel/components/ui/card.tsx
  main-web-vecel/components/ui/dialog.tsx
  main-web-vecel/components/ui/dropdown-menu.tsx
  main-web-vecel/components/ui/form.tsx
  main-web-vecel/components/ui/input.tsx
  main-web-vecel/components/ui/navigation-menu.tsx
  main-web-vecel/components/ui/popover.tsx
  main-web-vecel/components/ui/progress.tsx
  main-web-vecel/components/ui/sheet.tsx
  main-web-vecel/components/ui/skeleton.tsx
  main-web-vecel/components/ui/slider.tsx
  main-web-vecel/components/ui/switch.tsx
  main-web-vecel/components/ui/table.tsx
  main-web-vecel/components/ui/tabs.tsx
  main-web-vecel/components/ui/textarea.tsx
  main-web-vecel/components/ui/toast.tsx
  main-web-vecel/components/ui/toaster.tsx
  main-web-vecel/components/ui/tooltip.tsx
  main-web-vecel/hooks/use-toast.ts
  main-web-vecel/lib/utils.ts
  main-web-vecel/package-lock.json
  main-web-vecel/package.json
  main-web-vecel/pnpm-lock.yaml
  main-web-vecel/tailwind.config.ts
Labels: SWOC, ADVANCED

#89 feat: feature page implemented
  main-web-vecel/app/(root)/features/capture/page.tsx
  main-web-vecel/app/(root)/features/showcase/page.tsx
  main-web-vecel/app/(root)/features/trust/page.tsx
  main-web-vecel/app/(root)/layout.tsx
  main-web-vecel/app/layout.tsx
  main-web-vecel/app/page.tsx
  main-web-vecel/components/layout/navbar.tsx
  main-web-vecel/components/layout/sections/sponsors.tsx
  main-web-vecel/components/layout/sections/team.tsx
  main-web-vecel/package.json
  main-web-vecel/pnpm-lock.yaml
Labels: DWOC, level 3

#91 fix: issue in contributor image
  main-web-vecel/components/layout/sections/team.tsx
Labels: INTERMEDIATE, DWOC

#79 feat: integrate Resend API for contact form functionality in backend
  HeadPoseEstimation/anomaly_detection.py
  main-web-vecel/components/layout/sections/contact.tsx
  main-web-vecel/next.config.mjs
  main-web-vecel/package-lock.json
  main-web-vecel/package.json
  main-web-vecel/pnpm-lock.yaml
  requiremnts.txt
  server.py
Labels: SWOC, ADVANCED

#96 Implemented pnpm
  main-web-vecel/package-lock.json
Labels: jwoc, Easy
